### ISSUE TITLE
Export NIDM-Results as .nidm.zip

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm-results_spm#21]
As discussed on [NIDM call on Nov 2nd](https://docs.google.com/document/d/1L6zioNC3qdmUb1pSU2iUHzV-Vpzy3J89j5c110kIroE/edit?usp=sharing) (cf. also https://github.com/incf-nidash/nidm/issues/151), the NIDM-Results exporter should generate a `.nidm.zip` archive.

**Comment by nicholst** [comment]
Is this in the place of the (expanded) directory or in addition? Does the zip file contain a directory or just files flat?  If there is a directory what is the recommended naming convention and does the naming convention of that directory match that of the exported file name base (before .nidm.zip)?

I hate to re-open this can of worms, but is there any support for simply using a ".nidm" extension (like .docx, etc) that is actually a zip?

**Comment by cmaumet** [comment]
We agreed that for now the `.nidm.zip` would replace the expanded directory structure. I think that the zip should contain a flat list of files and there is no naming convention before the `.nidm.zip`.

I would say that it is worth keeping `.zip` in the extension so that the package can be recognised by any operating system (plus otherwise we would have to state in the spec that nidm is exported in .zip which we probably want to avoid...)

**Comment by cmaumet** [comment]
This was implemented by @gllmflndn.
